### ISSUE TITLE
Docker executor

### ISSUE THREAD

**Issue by fdellutri** [recteurlp/gitlab-ci-multi-runner-fedora#2]
Hi,
Do you plan to support docker executor?

Bests

**Comment by recteurlp** [comment]
Hi, 

Never tested it but it should already work

Mount the Host Docker Socket as a Volume in the Runner container

```bash
-v /var/run/docker.sock:/var/run/docker.sock
```

and change the RUNNER_EXECUTOR env variable for the initial registration
```bash
RUNNER_EXECUTOR=docker
```

You can also tweak your config file for docker if you're using persistence.

Best Regards,

**Comment by recteurlp** [comment]
Closing for lack of feedback.
